
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev?characterEncoding=UTF-8&serverTimezone=GMT
    username: dev
    password: 123456
mybatis:
  type-aliases-package: com.leakeyash.bootmybatis.model
  mapper-locations: classpath:/mybatis/mapper/*.xml
server:
  port: 8012
